version: '3'
services:
  app:
    container_name: svc-loker-be
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports: 
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - mysqldb
    networks:
      - loker

  mysqldb:
    image: mysql:8.0
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - loker

volumes:
  database_mysql:

networks:
  loker:
    driver: bridge
