CREATE TABLE position_levels (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    position_level VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);