CREATE TABLE employment_types (
     id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     type VARCHAR(100) NOT NULL,
     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);